### ISSUE TITLE
pypes cannot find TPM.nii

### ISSUE THREAD

**Issue by IKDRipp** [Neurita/pypes#24]
Error 'str' object has no attribute 'get'  for line 44, in spm_tpm_priors_path in File "/home/iripp/anaconda3/envs/neuro/lib/python3.6/site-packages/neuro_pypes-1.0.1-py3.6.egg/neuro_pypes/utils/environ.py", line 44, in spm_tpm_priors_path when attemptin to run the script.

**Comment by alexsavio** [comment]
What is the output of:
```
from nipype.interfaces import spm
spm.Info.version()
```
?

**Comment by IKDRipp** [comment]
>>> from nipype.interfaces import spm
171130-12:12:43,919 workflow DEBUG:
	 networkx 1.4 dev or higher detected
171130-12:12:43,933 interface DEBUG:
	 args_matlab
171130-12:12:43,933 interface DEBUG:
	 {'DISPLAY': ':1'}
>>> spm.Info.version()
171130-12:12:49,105 interface DEBUG:
	 {'DISPLAY': ':1'}

{'path': '/home/iripp/software/spm12/spm12_mcr/spm/spm12', 'name': 'SPM12', 'release': '7233'}


Isabelle Ripp
MSc Neuroscience, PhD candidate
Klinikum Rechts der Isar - Technische Universität München
Nuklearmedizin
Einsteinstr. 1
81675 München
Tel. +49-89-4140-7971
E-mail: isabelle.ripp@mri.tum.de


________________________________________
Von: Alexandre M. S. [notifications@github.com]
Gesendet: Donnerstag, 30. November 2017 10:11
An: Neurita/pypes
Cc: Ripp, Isabelle; Author
Betreff: Re: [Neurita/pypes] pypes cannot find TPM.nii (#24)

What is the output of:

from nipype.interfaces import spm
spm.Info.version()


?

**Comment by IKDRipp** [comment]
I copied tmp into spm_dir

**Comment by alexsavio** [comment]
you mean tpm? does it work now? If it works and you're fine with the solution, please close the issue clicking in 'Close and comment'. ;) Thanks!

**Comment by IKDRipp** [comment]
yes, I meant tpm, sorry. yes it works like this. The only error I get now is the one we know already:

  File "/home/iripp/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 188, in connect
    for edge in self._graph.in_edges_iter(destnode):
AttributeError: 'DiGraph' object has no attribute 'in_edges_iter'

**Comment by alexsavio** [comment]
Yes, I am working on it in #25. Could you try with the new nipype version? You can update it with: 
`pip install -U nipype` in your Python environment.
