### ISSUE TITLE
Error because of new nipype version

### ISSUE THREAD

**Issue by alexsavio** [Neurita/pypes#25]
```
File "/home/iripp/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 188, in connect
    for edge in self._graph.in_edges_iter(destnode):
AttributeError: 'DiGraph' object has no attribute 'in_edges_iter'
```

**Comment by alexsavio** [comment]
This seems like a problem inside nipype 👎  I will try with the new version that came out today.

**Comment by IKDRipp** [comment]
Yes, I am working on it in #25. Could you try with the new nipype version? You can update it with:
pip install -U nipype in your Python environment.

--> I am running it right now: It is right now at DEBUG:workflow:No resources available
.
.
.
DEBUG:workflow:No resources available
DEBUG:workflow:No resources available
DEBUG:workflow:No resources available
DEBUG:workflow:No resources available
DEBUG:workflow:No resources available


I will let you know later about what is happening further

**Comment by alexsavio** [comment]
Seems to be fixed already.
