### ISSUE TITLE
Fix Links referring to Github scripts on http://neuro-pypes.readthedocs.io/en

### ISSUE THREAD

**Issue by IKDRipp** [Neurita/pypes#26]
Fix Links referring to Github scripts on http://neuro-pypes.readthedocs.io/en

**Comment by alexsavio** [comment]
Thanks

-----
Alexandre Manhães Savio <alexsavio@gmail.com>

**Comment by alexsavio** [comment]
Now that I've fixed the docs generation the links have been fixed.
