### ISSUE TITLE
Crash of 01preprocessing.py

### ISSUE THREAD

**Issue by IKDRipp** [Neurita/pypes#29]
traits.trait_errors.TraitError: The trait 'in_file' of a GunzipInputSpec instance is an existing file name, but the path  '/home/iripp/data/raw/raw/healthy_stdpet/nb_141659/session_0/pet_fdg.nii.gz' does not exist.
Error setting node input:
Node: gunzip_pet
input: in_file
results_file: /home/iripp/data/raw/wd/main_workflow/_diagnosis_healthy_stdpet_session_id_session_0_subject_id_nb_141659/selectfiles/result_selectfiles.pklz
value: /home/iripp/data/raw/raw/healthy_stdpet/nb_141659/session_0/pet_fdg.nii.gz

**Comment by alexsavio** [comment]
Fixed in 0db310b4620c2d19485916c2c05e6338ce3f2356
